### ISSUE TITLE
Reproducibility cell cycle genes 

### ISSUE THREAD

**Issue by ktrns** [ktrns/scrnaseq#108]
Even if we use the same image, we get different results if we rerun the code a few weeks later. We figured that the order of cell cycle genes was different, and conclude that this is because of Biomart. 

We should sort the cell cycle genes to always get the same order... 

Or- remember to copy the old cell cycle genes annotation file into the new re-analysis.

**Comment by andpet0101** [comment]
I can confirm this. Changing the order of the cell cycle genes changes the cell cycles scores and phases which then may impact normalisation/cell cycle removal.
