### ISSUE TITLE
Read functions and how they convert names

### ISSUE THREAD

**Issue by ktrns** [ktrns/scrnaseq#15]
This doesn't seem quite right. Needs a double-check. Also, in the HTO script, we are not yet converting any names, not sure if it is even required.

**Comment by andpet0101** [comment]
I have fixed this in https://github.com/ktrns/scrnaseq/commit/eab50cf3dc4f2a18e25989df5c2c72305c870cbd. Names should now be correctly imported and converted.

As for the HTO script: Gene symbols are only needed in the prelim.analysis function, to define the mitochondrial content. In my opinion, we do not need this information here.

**Comment by ktrns** [comment]
I don't think we need the names for the HTO script. Let's leave it as is.
