### ISSUE TITLE
Read simple expression matrix as input

### ISSUE THREAD

**Issue by ktrns** [ktrns/scrnaseq#20]
@andpet0101 
Can we make it possible to read a simple expression matrix as input to our script? This would be useful for test datasets, which usually are saved as matrix.txt tab separated file, no further information. 

Or is this already possible with the SmartSeq-2 reading function?

**Comment by andpet0101** [comment]
Yes, the function for Smartseq2 data needs as input just a simple table/matrix. Also it does not have to be data generated by Smartseq2 but can be any technology - as long as the output is a table.

Maybe we should rename the functions: ReadCountsTable (counts by any tech) and ReadSparseMatrix (generated by cellranger)?

**Comment by ktrns** [comment]
I like ReadCountsTable. How about ReadCellrangerOutput to make it more precise? Or leave it at Read10xDataset since Cellranger is coupled to 10x anyhow.

**Comment by andpet0101** [comment]
ReadCountsTable: okay

Read10xDataset: kind of okay but in principle you can save every counts data from every technology in both formats. So they just represent two different ways of saving the counts data. The advantage of Read10xDataset/sparse matrices is that they are much smaller. It would be nice to reflect this in the name.

**Comment by ktrns** [comment]
Ok, then change it to ReadSparseMatrix. But we do need features.tsv and barcodes.tsv for this function to work, no?

**Comment by andpet0101** [comment]
Yes, because the matrix.mtx file of a sparse matrix does not contain cell or feature names.
