### ISSUE TITLE
Singularity container trial

### ISSUE THREAD

**Issue by colindaven** [ktrns/scrnaseq#23]
Hi @mariusrueve (I moved the issue from this fork to here)

I will try to create a prototype Singularity container recipe for this.

This is only one file which then needs to be built:

- apt packages need to be downloaded and installed
- R packages need to be built (takes 30-60minutes .... which is really a pain if you need to make adjustments)

I'll need to know the exact packages that are used:

a) Ubuntu packages (apt-get). Ubuntu version (20.04)

b) R packages

Marius answer - key packages

- library(shiny)
- library(Seurat)
- library(ggplot2)
- library(readxl)

**Comment by colindaven** [comment]
Status: it builds successfully with apt and R packages, but I need to get the singularity shiny etc stuff working.

@mariusrueve
What are the exact commands you use to start the a) shiny and b) alternative to shiny (was it dashboard or something similar ?) working  ?  Thanks

**Comment by colindaven** [comment]
I have built the app and parallelized the R compilation part within the container (container build time 40+ minutes reduced to about or less than 20 mins). Now waiting on @mariusrueve for Shiny and/or other app instructions.

**Comment by mariusrueve** [comment]
Ich habe die Idee vom flexdashboard erstmal hinten angestellt, da shiny deutlich flexibler ist und ich besser versuchen kann die Aufmachung von flexdashboard zu imitieren. 
Deshalb benutze ich shiny welches im script über `shinyApp(ui = ui, server = server)` und in der console über `runApp('scrnaseq_app.R')` gestartet wird.

**Comment by colindaven** [comment]
Hi @mariusrueve thanks for the reply. I'm missing this file but have made progress I think:

  cannot open compressed file 'pbmc_2020-06-08.rds', probable reason 'No such file or directory'

Where did you get this from and where is the app expecting this ? Thanks

```

singularity_scrna_app$ singularity exec ../scrnaseq_app.simg     R -e "options('shiny.port'=3838,shiny.host='0.0.0.0'); shiny::runApp('/data/scrnaseq/scrnaseq_app.R')"

R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> options('shiny.port'=3838,shiny.host='0.0.0.0'); shiny::runApp('/data/scrnaseq/scrnaseq_app.R')
Loading required package: shiny
Warning in gzfile(file, "rb") :
  cannot open compressed file 'pbmc_2020-06-08.rds', probable reason 'No such file or directory'
Error in gzfile(file, "rb") : cannot open the connection
Calls: <Anonymous> ... eval -> eval -> ..stacktraceon.. -> readRDS -> gzfile
Execution halted

```

**Comment by mariusrueve** [comment]
The file is too large for GitHub. I've uploaded the file to ownCloud: https://owncloud.gwdg.de/index.php/s/rRawkhIOVe1T5qi. 

Currently the file gets loaded in line 32 `sc = readRDS(file = "pbmc_2020-06-08.rds")` and therefore is expected to be in the working directory.

**Comment by colindaven** [comment]
Hi @ktrns @andpet0101 

the singularity repo is here https://github.com/colindaven/singularity_scrna_app
and works AFAIK

Features:
-generates a container with Ubuntu 20.04 and R
-downloads and serves the code from Marius' branch (can and should be changed after merging the repos)
-port which it is being served on can be changed in the script
-however no password protection exists at present (perhaps use apache .htaccess if nothing better exists in shiny ?)

I can see that the website is being served (I get a GUI), but further testing should be done by those with actual data, eg. Torsten, @mariusrueve Oliver etc. ( I don't have any data).

So, can we can integrate this in the repo after testing ? Where ? A singularity subdirectory ?

**Comment by colindaven** [comment]
Issue continued in new repo https://github.com/MHH-RCUG/scrnaseq_app
