### ISSUE TITLE
Consistency in filter criteria and order of marker genes needs improvement

### ISSUE THREAD

**Issue by Oliver-D-B** [ktrns/scrnaseq#39]
-	It is confusing for end-users that the actual filter criteria that yield in candidates of the Excel output file „Markers.xlsx“ are quite different from what is currently applied for the bar graph panel “Number of DEGs per cell cluster”. This should be harmonized.

-	At present, there are some obvious inconsistencies in marker gene order comparing the three different panels, namely  1) global heatmap 2) Excel output file „Markers.xlsx“ 3) table “Top 2 DEGs per cell cluster”. Markers in 1) are sorted acc. to decreasing “avg_logFC”, markers in  2)  acc. to increasing “p_val”, markers in 3) were selected (as the top two) based on “avg_logFC” but were intrinsically ordered according to increasing “p_val”(as in “Markers.xlsx). The top gene selection for showing individual marker genes (e.g. in the ridge plot) is again based on decreasing “avg_logFC” similar as for the  global heatmap. To improve general and intuitive orientation within the report this should be harmonized.

**Comment by ktrns** [comment]
Hi Oliver, 

Thanks a lot for your useful feedback! 
I will have a look into this and decide on one way of ordering genes. With regard to point 1, the numbers should match, so I will definitely have a look what is going on. 

Best and thanks again, 
Katrin

**Comment by Oliver-D-B** [comment]
Thanks a lot Katrin,

regarding point 1, so far no matchuing in numbers is realistic due to different filter criteria applied for the two approaches.

**Comment by ktrns** [comment]
I see, we write out all markers that come out of the FindAllMarkers function, but then apply a somewhat more stringent threshold. We plot the number of marker genes that pass that threshold and use the resulting gene sets for enrichment analysis. I will discuss this with Andreas, too.

**Comment by Oliver-D-B** [comment]
Actually, the Excel outputs 'Markers.xlsx' contain genes that were identified with the 'FindAllMarkers' function, which asks for:

1) min.pct=0.25
2) logfc.threshold=0.25 (which means 1.19-fold, quite counterintuitive)

but one additional criterion is:

3) pValue<= 0.01 (presumably coming from the 'MAST' statistics test)

How about changing the logfc.threshold to 0.585 (1.5-fold, more intuitive) and using this very set of thresholds consistently for all: 
a) 'Markers.xlsx'
b) bar graph panel 'Number of DEGs per cell cluster' (description then needs adaptation here to include all three criteria accordingly)  
c) input for enrichment analysis

Some different criteria or settings might also be fine, but consistency would be really good to have.
