### ISSUE TITLE
(Re)Integration of the violin plots

### ISSUE THREAD

**Issue by Oliver-D-B** [ktrns/scrnaseq#40]
-	The “violin plots” as examples for marker genes of individual clusters are extremely valuable and do show aspects of the data that no other panel is able to. Thus, they should still be (re-)integrated into the standard report (as we have already realized in a recently ‘launched’ RCUG-specific version of the script/report).

**Comment by ktrns** [comment]
Hi again, 

What would you say is a violin plot showing that a ridge plot wouldn't? We could add a fifth tab for showing a violin plot for the top gene per cluster? That would be no problem at all. You could also send me a screenshot how you guys solved it for now.  

Thanks again, 
Katrin

**Comment by Oliver-D-B** [comment]
Hi Katrin,

I tried to show some good argumets for the violin plot,
best regards,
Oliver

[(Re)Integration of the violin plots #40_ODB.pptx](https://github.com/ktrns/scrnaseq/files/4989795/Re.Integration.of.the.violin.plots.40_ODB.pptx)

**Comment by tglomb** [comment]
Hi everybody,  
I just wanna let you know that I'm going to reintegrate the violin plots.  

Best
Torsten
