### ISSUE TITLE
Output of functional enrichment results is not informative yet

### ISSUE THREAD

**Issue by Oliver-D-B** [ktrns/scrnaseq#41]
-	The currently contained table as output of the Functional enrichment analysis is not really informative (regarding actual results) and should be removed or modified to better reflect an overview of most strongly enriched gene sets or categories (e.g. GO terms) per cluster (to directly reflect the outcome of this specific approach).

**Comment by ktrns** [comment]
Hi Oliver, 

Can you specify in what way it is not informative? I just looked into some of the files, and can see that for some reason the files list terms, where an overlap is found but however that overlap is non-significant. We could limit the output excel files to significant terms. Is that what you mean? 

In addition, I added a table to the output HTML that contains the top term per geneset and database. 

Best
Katrin

**Comment by Oliver-D-B** [comment]
Dear Katrin,

please just forget and close this issue. I was referring to the report itself (not to the Excel output) but just regarding an older version where there was not yet such a results table contained.
