### ISSUE TITLE
Even more explanatory / introductory texts for unexperienced users

### ISSUE THREAD

**Issue by Oliver-D-B** [ktrns/scrnaseq#43]
- I would recommend integrating even more explanatory text sections for the unexperienced end-users into the report (e.g. such as from the current original vignette "Seurat - Guided Clustering Tutorial" or some more own ones) in addition to the explanations already included. Since such text blocks in the report will then increase in proportion and space (with a general negative impact on visual clarity), one could consider making these explanatory information either visible - or hiding it (similar as already implemented with the source code buttons in the html files). It may be most intuitive and understandable for unexperienced end-users to have such an explanatory (introductory) text block (respectively the button for it) before each visualization panel or analysis step (in part already realized, I know).

**Comment by kosankem** [comment]
I have inspected the descriptions/explanatory text that are in the script so far. Attached you can find a word document with marked changes/extensions to the text, only [Text to script.docx](https://github.com/ktrns/scrnaseq/files/6477933/Text.to.script.docx). In general, I also think that it would be helpful for unexperienced end-users to have some more explanations at specific parts, especially if we consider that those users should be able to ask for specific modifications of the used parameters or do them by themselves via Marius App in the future. To not inflate the text content of the report unnecessarily, I would insert most of the additional text as extendable fields (see word document).
The additional explanations are mainly inspired by Seurat and GTN Smörgåsbord (Galaxy) tutorials and address those aspects that the questions of my student or colleagues have lain in. 
Please let me know if you find these text extensions appropriate and helpful and if you would like to include all or some of them into the script. I could take care of inserting them at the correct positions then if that is of any help.
Links to the tutorials:
-	https://training.galaxyproject.org/training-material/topics/transcriptomics/tutorials/scrna-scanpy-pbmc3k/tutorial.html?utm_source=smorgasbord&utm_medium=website&utm_campaign=smorgasbord2021
-	https://satijalab.org/seurat/articles/pbmc3k_tutorial.html

**Comment by kosankem** [comment]
[Text to script.docx](https://github.com/ktrns/scrnaseq/files/6477952/Text.to.script.docx)

**Comment by ktrns** [comment]
Dear @kosankem, 

Thanks a lot for looking into the documentation! We are a bit busy with ongoing projects right now, but will soon look into your suggestions and let you know. 

Again, thanks a lot! 
Katrin

**Comment by ktrns** [comment]
Dear @kosankem, 

My plan is to look at your documentation soon, hopefully starting tomorrow morning. 

Do you already know how to implement drop-down text boxes? If not, could you check this out? 

Thanks a lot,
Katrin

**Comment by kosankem** [comment]
Dear @ktrns 
It seems fairly simple to integrate the drop-down:

(In R markdown)

<details>
  <summary>Click to expand!</summary>
  
  ## Heading of the text that should be integrated
  Text
</details>

[drop_down.txt](https://github.com/ktrns/scrnaseq/files/6562205/drop_down.txt)


Note: Make sure you have an empty line after the closing </summary> tag, otherwise the markdown/code blocks won't show correctly. Make sure you have an empty line after the closing </details> tag if you have multiple collapsible sections.

Please, let me know if I can help to integrate some of the text.

**Comment by ktrns** [comment]
Dear @kosankem, 

I carefully went through all the text, and am now circulating it with a few colleagues to proof-read. After the text is finalised, it would be very helpful if you could take over adding the text to the latest version of the main script? 

I will let you know once I have the final version of the text. 

Best wishes & thanks
Katrin

**Comment by kosankem** [comment]
Dear @ktrns,
no problem. I can later add the texts to the script. 
Best wishes,
Maike
