### ISSUE TITLE
Identified celltype-specific markers are sometimes misleading due to current selection criteria

### ISSUE THREAD

**Issue by Oliver-D-B** [ktrns/scrnaseq#44]
- The very central heatmap of the top 10 (if available) differentially expressed marker genes per cluster - along with the underlying filtering criteria and visualization settings applied - is sometimes misleading for certain projects and specific data structures. There are cases, where the identified ‘celltype-specific markers’ are questionable (in the sense to 'undoubtedly fullfill this very property in some different respects). This still needs some further improvement (mainly at the level of the underlying selection criteria regarding: “what are the best criteria to call a gene a cluster-specific marker?"
- This general issue is not trivial at all and needs some extensive deliberations.

**Comment by ktrns** [comment]
The current criteria are set in the project-specific parameter chunk: 
```
# Thresholds to define differentially expressed genes 
param$padj = 0.05
param$log2fc = log2(1.5)
```

Would you be able to pull up some examples, where you think the selection is misleading? That might make it clearer and easier to decide on an alternative strategy. 

Thanks again!

**Comment by Oliver-D-B** [comment]
Hi Katrin,

I am not so sure if those above mentioned criteria are the ones the are currently applied. However, again a more consistent general use of filter criteria for all relevant outputs would be really good to have (see also Issue #39 ).

However, please find attached an example that questions the current way to define 'cluster-specificity' (or at least suggests one alternative and additional way to define this property with more stringency or 'mutual exclusiveness')

[Identified celltype-specific markers are sometimes misleading due to current selection criteria (#44)_ODB.pptx](https://github.com/ktrns/scrnaseq/files/4993971/Identified.celltype-specific.markers.are.sometimes.misleading.due.to.current.selection.criteria.44._ODB.pptx)

**Comment by ktrns** [comment]
Hi Oliver, 

Thanks for making the pptx to show an example. I know what you mean. 

We could add an additional filter parameter. Having said that, these plots also help to judge whether the clustering resolution is good. Imagine, cluster 0-4 are somewhat similar, getting similar marker genes, which aren't exclusive but yet significant. We might have to change the resolution so those clusters become one cluster. 

As a client, I would probably want to see all genes that come out as significant based on the differential gene expression analysis even if some are shared with other clusters, no? 

How about we add a variable that explains the distance to the next cluster? For example the smallest fold-change we find, comparing a cluster of interest to each of the other clusters. We can add this variable to the markers.xlsx output. This way, the user can use the Excel table and filter afterwards for exclusive genes. They'd still be in the heat map this way though.

**Comment by ktrns** [comment]
Hi @Oliver-D-B, 

What shall we do with this issue? Having a little more experience myself by now, I use the DEG plots to judge whether the cluster resolution is good. I especially use the resulting Dotplot to see if we can find clear markers. If not, I have to re-run the workflow with a different cluster resolution. This is a key step, before we deliver the results to our clients. 

So if I was deciding, I would just close this issue and don't change the way we select DEGs. 

Let me know what you think,
Katrin

**Comment by ktrns** [comment]
Hi @Oliver-D-B, 

Can we close the issue? In other words, does the above explanation make sense to you? 

Best wishes
Katrin
