### ISSUE TITLE
Some (sub-)panels (e.g. of ridge plot, violin plot) get strongly compressed the more clusters were identified

### ISSUE THREAD

**Issue by Oliver-D-B** [ktrns/scrnaseq#50]
Depending on the identified number of clusters, some (sub-)panels (e.g. of the ridge plot and the violin plot) get strongly compressed the more clusters have been identified in a current situation (see example below). Therefore, some different way to define the space and dimensions in the html report is required.

**Comment by Oliver-D-B** [comment]
[Some (sub-)panels (e.g. of ridge plot, violin plot) get strongly compressed the more clusters were identified #50_ODB.pptx](https://github.com/ktrns/scrnaseq/files/4994126/Some.sub-.panels.e.g.of.ridge.plot.violin.plot.get.strongly.compressed.the.more.clusters.were.identified.50_ODB.pptx)

**Comment by ktrns** [comment]
Yes, that needs to be changed for sure. Thanks for spotting the issue.
