### ISSUE TITLE
Integration versus merging, CellCycleScoring on individual samples or merged dataset?

### ISSUE THREAD

**Issue by ktrns** [ktrns/scrnaseq#55]
- We need to be wise with integration. To integrate data from several samples, there should be some cells that overlap the samples, e.g. skin tissue from mouse sequenced in two different labs. The respective paper to read is: Comprehensive Integration of Single-Cell Data (Cell). 
- If we only "merge" several samples, we are currently re-running SCTransform. In addition, we might want to re-run CellCycleScoring, because it makes a difference whether this is run per sample, or run for the whole dataset. It should make more sense to move the complete merge chunk up to after filtering, as we anyway have to re-run normalisation. It doesn't make much sense to normalise individual samples if we don't use this at all. 
- What makes more sense? CellCycleScoring per sample, or for the whole merged dataset? The results differ quite a bit, not in terms of scores, but in terms of the assigned phase. If the scores wobble around 0, phase can easily change. This is discussed in: https://github.com/satijalab/seurat/issues/2277

**Comment by duocang** [comment]
@ktrns 
Any experience or thoughs you can share？

**Comment by ktrns** [comment]
Dear @duocang, 

Apologies for the late reply. Can you make your question more specific? 

With the latest version of the workflow, we can tell the script to re-score the cell-cycle after multiple samples have been combined. Conceptually, I think this makes more sense, so I usually do it. So far, I had one dataset, where the samples were very different, and we skipped re-scoring. 

Does this help? Let me know. 

Best wishes
Katrin

**Comment by duocang** [comment]
@ktrns 

Hi Katrin,
I would like to know the idea of “CellCycleScoring per sample, or for the whole merged dataset?”. Thank you for your reply.

I was very confused about this. I tried both but they seem to be different in a way. I will check again and let you know what I have. 

Best regards
Xuesong

**Comment by ktrns** [comment]
Dear @duocang,

Yes the results can differ quite a bit, especially when the samples are very different. 

In that one project I mentioned above, samples were different, and my client said that the classified cell cycle phases made more sense biologically speaking, when calculated separately per sample. 

For all other projects, I re-score cell cycle after samples have been merged, as we are looking at the UMAP of all samples. In a way, I want the cell cycle phases to be determined together to make them relatable if that makes sense. 

Let me know what you have, looking forward to some other experiences. 
Katrin
