### ISSUE TITLE
in case of few cells error in Seurat::RunPCA

### ISSUE THREAD

**Issue by dimialex** [ktrns/scrnaseq#66]
Dear all,

in the case of a project with few cells in a sc-RNA-seq dataset, I am getting the same error as in:

https://github.com/satijalab/seurat/issues/1914

I'm correcting it via editing the npcs argument (default npcs=50), such as follows:

sc = Seurat::RunPCA(sc, features=Seurat::VariableFeatures(object=sc), verbose=FALSE, npcs=14)

Best,

Dimitra

**Comment by andpet0101** [comment]
* `RunPCA now` will always run with `min(50, ncol(sc))`, plots will adjust as well
* Integration: `k.anchor`, `k.filter` and `k.weight` are set to 200, 100 and 5 or if lower the number of cells
* `param$pc_n` will be set to `min(param$pc_n, ncol(sc))`
