### ISSUE TITLE
Split HTO demultiplexing and actual scrnaseq analysis

### ISSUE THREAD

**Issue by ktrns** [ktrns/scrnaseq#9]
We will split the code again into two parts such that HTO demultiplexing will generate a standalone small report, and generates demultiplexed data that can be processed with the main scrnaseq analysis script.

**Comment by tglomb** [comment]
Hi Katrin,  
what are your plans about splitting the code? Do you want to have scrnaseq.Rmd as main script and control the moduls to run via settings?  
I would like to add some changes to code but would like to clarify that before.

**Comment by ktrns** [comment]
Hi Torsten, 

I am very sorry I did not see your message! We merged our HTO-related code back to master. We added a second script `scrnaseq_hto.Rmd` to demultiplex the data and generate a HTO-related report. The main script `scrnaseq.Rmd` can then be run for demultiplexed data. 

I have to change some settings in my GitHub to be notified about comments. Again, sorry to have missed this one. 

What changes/code have you been adding?
