### ISSUE TITLE
Tables displaying excluded cells/feature numbers with percentages

### ISSUE THREAD

**Issue by kosankem** [ktrns/scrnaseq#95]
Wir fänden es übersichtlicher und intuitiver, wenn in den Tabellen zu den „Number of excluded cells“ und „Number of excluded genes“ eine zusätzliche Spalte mit den jeweils ‚remaining percentages‘ enthalten wäre. 
Ich habe das zurzeit so umgesetzt:
(Basierend auf der Script version Anfang Juni)
[Percentage of remaining cells and features.txt](https://github.com/ktrns/scrnaseq/files/6740432/Percentage.of.remaining.cells.and.features.txt)

**Comment by ktrns** [comment]
Dear Maike, 

Thanks (and no thanks :-) - joke) for inserting all issues. 

Another column sounds good, go for it. Best if you use the latest master version and insert the new changes there. It will be easier to do small PRs. 

Best & thanks
Katrin
