### ISSUE TITLE
Diverse cluster resolutions

### ISSUE THREAD

**Issue by kosankem** [ktrns/scrnaseq#97]
Wir fänden es hilfreich für unsere Kunden, wenn sie neben der ‚Main‘ Resolution, mit der im Report weitergearbeitet wird, auch ein Eindruck für den Effekt der Wahl von anderen ‚Test‘ Resolutions vermittelt bekommen würden. Zudem ist es auch für mich hilfreich, wenn ich das Skript laufen lasse oder kontrolliere, direkt die Ausgabe mehrerer Resolutions zu sehen, um ggf. die Analyse besser anpassen zu können. Die Darstellung dieser Testresolutions ist optional und kann in der Parameterliste definiert werden. 
Ich habe dies zurzeit so umgesetzt:
(Basierend auf der Skriptversion von Anfang Juni)
[Diverse_resolutions.txt](https://github.com/ktrns/scrnaseq/files/6740520/Diverse_resolutions.txt)

**Comment by ktrns** [comment]
Could you possibly add an image, so it is easier to see what you mean? 

Based on our previous conversations, I think I know what you mean and I'd be open to it. @andpet0101 What do you think?

**Comment by kosankem** [comment]
Basically it looks like this
![grafik](https://user-images.githubusercontent.com/79709511/123958428-598e4e00-d9ad-11eb-95c4-a34637195da6.png)

**Comment by ktrns** [comment]
Yeah, why not. 

One thing to think about though. Just seeing different clusterings doesn't really help deciding whether the clustering is any useful. You only know that once you see that you have good and clear marker genes. It gives a feeling though on how much the clustering can change. 

By the way @fabianrost84 - What do you think on this one?

**Comment by fbnrst** [comment]
Personally, I think this is so much dependent on the data that the analyst should decide on one resolution. But this would be done by choosing one main resolution, right? 10X does something similar by choosing different ks for k-means clustering. 
I don't find it super-important (just personal opinion), but nothing speaks against adding this info.
