### ISSUE TITLE
UMAPs displaying samples separately

### ISSUE THREAD

**Issue by kosankem** [ktrns/scrnaseq#98]
Besonders im Falle der Integration von Samples mit hohen Zellzahlen ist es oft nicht möglich, die Aufteilung der relativen Zellmengen pro Cluster und Sample in der UMAP „Coloured by sample“ erkennen zu können, da die Probe, welcher die ‚Vordergrundfarbe‘ zugeordnet wurde, die anderen (rein visuell) überdeckt. Daher wollen wir vorschlagen, zusätzliche Tabs mit den UMAPs splitted by Samples einzufügen. Gerade im Vergleich von zwei Bedingungen (z.B. Control vs Disease) ist das eine schöne zusätzliche Visualisierung von Unterschieden in der Zugehörigkeit zu Clustern.
Zurzeit habe ich das so umgesetzt:
(Basierend auf der Skriptversion von Anfang Juni)
[UMAPs seperately per sample.txt](https://github.com/ktrns/scrnaseq/files/6740549/UMAPs.seperately.per.sample.txt)

**Comment by ktrns** [comment]
Fine for me. What do you think @andpet0101? 

You could have a look at the updated HTO html. Andreas added a plot like this: a UMAP split to multiple rows and columns.

**Comment by kosankem** [comment]
Basically it looks like this
![grafik](https://user-images.githubusercontent.com/79709511/123958607-88a4bf80-d9ad-11eb-963b-4349b65810c1.png)
and
![grafik](https://user-images.githubusercontent.com/79709511/123958669-9d815300-d9ad-11eb-87e2-578aec5558d0.png)

**Comment by ktrns** [comment]
Yes, I like it. You'd have to implement it in a way that with more samples it uses multiple rows. Did you already do this?

**Comment by kosankem** [comment]
As long as seurat does not split into multiple rows by default, I haven't done it. But I can take care of it and test it.
