### ISSUE TITLE
pt.size

### ISSUE THREAD

**Issue by kosankem** [ktrns/scrnaseq#99]
Gerade bei größeren Zellzahlen, hat sich die pt.size 0.1, und nicht 1 wie es zurzeit im Skript der Fall ist, für uns als bessere Wahl dargestellt, auch um visuellen Überlagerungseffekte weiter zu minimieren.

**Comment by ktrns** [comment]
We could add the point size as a parameter? I often analyse SmartSeq-2 data and wouldn't want to have the dots any smaller.
